# EXTENDED FIGURE 7

In [ ]:
import os
import requests
import pandas as pd
import numpy as np
import nglui
from statistics import mean
import matplotlib.pyplot as plt
import seaborn as sns
import cloudvolume
from caveclient import CAVEclient


client = CAVEclient('minnie65_phase3_v1')
client.info.get_datastack_info()


pd.options.display.max_rows = None
pd.options.display.max_columns = None

#Load dataframe
synapse_table = pd.read_feather("ET_extended_synapse_table.feather")

In [3]:
# Statistical analysis
# Multiple comparisions

data = [synapse_table.query("consensus_subclass == '5P-ET'")['size'].values,
              synapse_table.query("consensus_subclass == '5P-IT'")['size'].values,
              synapse_table.query("consensus_subclass == '5P-NP'")['size'].values,
              synapse_table.query("consensus_subclass == '6P'")['size'].values,
              synapse_table.query("consensus_subclass == 'BC'")['size'].values,
              synapse_table.query("consensus_subclass == 'MC'")['size'].values]


#perform Dunn's test using a Bonferonni correction for the p-values
import scikit_posthocs as sp
sp.posthoc_conover(data, p_adjust = 'bonferroni')

          1         2         3             4             5             6
1  1.000000  1.000000  1.000000  8.112115e-01  1.000000e+00  1.000000e+00
2  1.000000  1.000000  0.928235  1.686539e-04  1.122352e-01  1.904448e-01
3  1.000000  0.928235  1.000000  4.148239e-05  1.000000e+00  1.000000e+00
4  0.811211  0.000169  0.000041  1.000000e+00  6.713862e-13  1.019631e-10
5  1.000000  0.112235  1.000000  6.713862e-13  1.000000e+00  1.000000e+00
6  1.000000  0.190445  1.000000  1.019631e-10  1.000000e+00  1.000000e+00